# Generated by Django 4.0 on 2021-12-23 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('avg_rating', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rates_number', models.BigIntegerField()),
            ],
        ),
    ]
