# Generated by Django 4.0 on 2021-12-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='avg_rating',
            field=models.FloatField(),
        ),
    ]
